/*
 * Generated by Digiblock. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module PriorityEncoder2 (
    input in0,
    input in1,
    input in2,
    input in3,
    output reg [1:0] num,
    output any
);
    always @ (*) begin
        if (in3 == 1'b1)
            num = 2'h3;
        else if (in2 == 1'b1)
            num = 2'h2;
        else if (in1 == 1'b1)
            num = 2'h1;
        else 
            num = 2'h0;
    end

    assign any = in0 | in1 | in2 | in3;
endmodule

module encoder1 (
  input D_0, // data bit 0.
  input D_1, // data bit 1.
  input D_2, // data bit 2.
  input D_3, // data bit 3.
  output a,
  output [1:0] y
);
  PriorityEncoder2 PriorityEncoder2_i0 (
    .in0( D_0 ),
    .in1( D_1 ),
    .in2( D_2 ),
    .in3( D_3 ),
    .num( y ),
    .any( a )
  );
endmodule
