/*
 * Generated by Digiblock. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module \Full adder  (
  input A_i, // first bit to add
  input B_i, // second bit to add
  input \C_{i-1} , // carry in
  output C_i, // carry bit
  output S_i // sum

);
  wire s0;
  assign s0 = (A_i ^ B_i);
  assign S_i = (s0 ^ \C_{i-1} );
  assign C_i = ((A_i & B_i) | (s0 & \C_{i-1} ));
endmodule
